azure:
  settings_win:
    variables:
      SET_PAGEFILE: 'True'
      CONDA_BLD_PATH: C:\\bld\\
      MINIFORGE_HOME: C:\Miniforge
build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
github_actions:
  self_hosted: true
  triggers:
    - push
    - pull_request
provider:
  linux_64: github_actions
  linux_aarch64: default
  linux_ppc64le: default
test: native_and_emulated
conda_install_tool: pixi
conda_build_tool: rattler-build
