conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
github_actions:
  triggers:
    - push
    - pull_request
provider:
  linux_aarch64: default
  osx_arm64: default
conda_install_tool: pixi
conda_build_tool: rattler-build
workflow_settings:
  pagefile_size:
    - os: win
      value: 16
  build_workspace_dir:
    - provider: azure
      os: win
      value: C:\\bld\\
  tools_install_dir:
    - provider: azure
      os: win
      value: C:\Miniforge
