azure:
  settings_win:
    variables:
      SET_PAGEFILE: 'True'
build_platform:
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
github_actions:
  self_hosted: true
  triggers:
  - push
  - pull_request
provider:
  linux_64: github_actions
